import { Inter } from 'next/font/google';
import { caniculeDisplayB, hakgoansimMulgyeolB, pretendard } from '@hehe/hds/tokens/fonts';
import './globals.css';
import type { Metadata } from 'next';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const fontVars = [hakgoansimMulgyeolB.variable, pretendard.variable, caniculeDisplayB.variable];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={fontVars.join(' ')}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
